## Level 2: Data Cleaning and Feature Creation

### Objective
To clean the train journey dataset, handle missing and duplicate records, convert time information into a machine-learning-friendly format, calculate journey duration, and create useful input features for machine learning.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Dataset1.csv")
df

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [6]:
df = pd.read_csv("Dataset1.csv")
df

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [7]:
df.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

## Task 2.1: Handling Missing Values and Duplicate Records

In [8]:
missing_values = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing_values

                Missing_Count  Missing_Percentage
SN                          0                 0.0
Train_No                    0                 0.0
Station_Code                0                 0.0
1A                          0                 0.0
2A                          0                 0.0
3A                          0                 0.0
SL                          0                 0.0
Station_Name                0                 0.0
Route_Number                0                 0.0
Arrival_time                0                 0.0
Departure_Time              0                 0.0
Distance                    0                 0.0

In [9]:
duplicate_count = df.duplicated().sum()

print("Total Duplicate Records:", duplicate_count)

Total Duplicate Records: 0

In [10]:
df = df.drop_duplicates().reset_index(drop=True)
df

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655

In [11]:
print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (186074, 12)

## Task 2.2: Converting Arrival and Departure Times

In [12]:
print("Arrival Time Examples:")
print(df["Arrival_time"].head(20).tolist())

print("\nDeparture Time Examples:")
print(df["Departure_Time"].head(20).tolist())

Arrival Time Examples:
['00:00:00', '11:06:00', '11:28:00', '12:10:00', '00:00:00', '21:04:00', '21:26:00', '22:25:00', '19:40:00', '20:18:00', '20:40:00', '21:16:00', '21:38:00', '21:54:00', '22:18:00', '22:40:00', '22:56:00', '23:52:00', '00:34:00', '01:10:00']

Departure Time Examples:
['10:25:00', '11:08:00', '11:30:00', '00:00:00', '20:30:00', '21:06:00', '21:28:00', '00:00:00', '19:40:00', '20:20:00', '20:42:00', '21:18:00', '21:40:00', '21:56:00', '22:20:00', '22:42:00', '22:58:00', '23:57:00', '00:36:00', '01:12:00']

In [13]:
df["Arrival_time"] = pd.to_datetime(
    df["Arrival_time"],
    format="%H:%M:%S",
    errors="coerce"
)

df["Departure_Time"] = pd.to_datetime(
    df["Departure_Time"],
    format="%H:%M:%S",
    errors="coerce"
)

In [14]:
df[["Arrival_time", "Departure_Time"]].head()

         Arrival_time      Departure_Time
0 1900-01-01 00:00:00 1900-01-01 10:25:00
1 1900-01-01 11:06:00 1900-01-01 11:08:00
2 1900-01-01 11:28:00 1900-01-01 11:30:00
3 1900-01-01 12:10:00 1900-01-01 00:00:00
4 1900-01-01 00:00:00 1900-01-01 20:30:00

In [16]:
df = df.sort_values(
    ["Train_No", "Route_Number", "SN"]
).reset_index(drop=True)
df

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,8,99908,AKRD,195,176,157,138,AKURDI,1,1900-01-01 23:30:00,1900-01-01 23:31:00,19
186070,9,99908,DEHR,220,196,172,148,DEHU ROAD,1,1900-01-01 23:35:00,1900-01-01 23:36:00,24
186071,10,99908,BGWI,240,212,184,156,BEGDAEWAI,1,1900-01-01 23:39:00,1900-01-01 23:40:00,28
186072,11,99908,GRWD,255,224,193,162,GHORAWADI,1,1900-01-01 23:41:00,1900-01-01 23:42:00,31
186073,12,99908,TGN,270,236,202,168,TALEGAON,1,1900-01-01 23:50:00,1900-01-01 00:00:00,34

In [18]:
train_journey = df.groupby("Train_No").agg(
    Start_Station=("Station_Name", "first"),
    End_Station=("Station_Name", "last"),
    Start_Time=("Departure_Time", "first"),
    End_Time=("Arrival_time", "last"),
    Total_Distance=("Distance", "max"),
    Number_of_Stops=("Station_Name", "count")
).reset_index()

In [19]:
train_journey.head(10)

,Train_No,Start_Station,End_Station,Start_Time,End_Time,Total_Distance,Number_of_Stops
0,107,SAWANTWADI R,MADGOAN JN.,1900-01-01 10:25:00,1900-01-01 12:10:00,78,4
1,108,MADGOAN JN.,SAWANTWADI R,1900-01-01 20:30:00,1900-01-01 22:25:00,83,4
2,128,MADGOAN JN.,CHHATRAPATI,1900-01-01 19:40:00,1900-01-01 17:45:00,978,22
3,290,DELHI-SAFDAR,DELHI-SAFDAR,1900-01-01 18:30:00,1900-01-01 02:30:00,2694,14
4,401,AURANGABAD,VARANASI JN.,1900-01-01 21:30:00,1900-01-01 10:00:00,1618,12
5,421,LUCKNOW JN.,SHRI MATA VA,1900-01-01 23:00:00,1900-01-01 08:00:00,1276,5
6,422,SHRI MATA VA,LUCKNOW JN.,1900-01-01 11:45:00,1900-01-01 14:30:00,1277,5
7,477,SIRSA,SIRSA,1900-01-01 12:10:00,1900-01-01 15:20:00,2616,14
8,502,RAJENDRANAGA,AMBALA CANTT,1900-01-01 10:30:00,1900-01-01 09:30:00,1206,9
9,504,PATNA JN.,BATHINDA JN,1900-01-01 09:00:00,1900-01-01 10:00:00,1313,3

In [20]:
print(
    "Arrival 00:00:00:",
    (df["Arrival_time"].dt.strftime("%H:%M:%S") == "00:00:00").sum()
)

print(
    "Departure 00:00:00:",
    (df["Departure_Time"].dt.strftime("%H:%M:%S") == "00:00:00").sum()
)

Arrival 00:00:00: 2003
Departure 00:00:00: 1970

In [21]:
df[
    (df["Arrival_time"].dt.strftime("%H:%M:%S") == "00:00:00") |
    (df["Departure_Time"].dt.strftime("%H:%M:%S") == "00:00:00")
][[
    "Train_No",
    "Route_Number",
    "Station_Name",
    "Arrival_time",
    "Departure_Time",
    "Distance"
]].head(20)

,Train_No,Route_Number,Station_Name,Arrival_time,Departure_Time,Distance
0,107,1,SAWANTWADI R,1900-01-01 00:00:00,1900-01-01 10:25:00,0
3,107,1,MADGOAN JN.,1900-01-01 12:10:00,1900-01-01 00:00:00,78
4,108,1,MADGOAN JN.,1900-01-01 00:00:00,1900-01-01 20:30:00,0
7,108,1,SAWANTWADI R,1900-01-01 22:25:00,1900-01-01 00:00:00,83
990,4831,1,JODHPUR JN.,1900-01-01 00:00:00,1900-01-01 13:30:00,0
1011,4831,1,HARIDWAR JN,1900-01-01 10:45:00,1900-01-01 00:00:00,882
1328,5715,1,NEW JALPAIGU,1900-01-01 00:00:00,1900-01-01 03:00:00,0
1329,5715,1,KISHANGANJ,1900-01-01 05:10:00,1900-01-01 00:00:00,87
1330,5716,1,KISHANGANJ,1900-01-01 00:00:00,1900-01-01 04:00:00,0
1331,5716,1,NEW JALPAIGU,1900-01-01 06:30:00,1900-01-01 00:00:00,87
1332,5719,1,KATIHAR JN.,1900-01-01 00:00:00,1900-01-01 23:15:00,0
1342,5719,1,SILIGURI JN.,1900-01-01 03:15:00,1900-01-01 00:00:00,204
1343,5720,1,SILIGURI JN.,1900-01-01 00:00:00,1900-01-01 18:00:00,0
1353,5720,1,KATIHAR JN.,1900-01-01 23:00:00,1900-01-01 00:00:00,205
1870,6081,1,COIMBATORE,1900-01-01 00:00:00,1900-01-01 13:35:00,0
1873,6081,1,POLLACHI,1900-01-01 14:45:00,1900-01-01 00:00:00,45
1874,6082,1,POLLACHI,1900-01-01 00:00:00,1900-01-01 15:05:00,0
1877,6082,1,COIMBATORE,1900-01-01 16:15:00,1900-01-01 00:00:00,45
1878,6412,1,DELHI-SAFDAR,1900-01-01 00:00:00,1900-01-01 11:10:00,0
1898,6412,1,PAYYANUR,1900-01-01 16:20:00,1900-01-01 00:00:00,2462

In [22]:
df.groupby("Train_No").tail(1)[[
    "Train_No",
    "Station_Name",
    "Arrival_time",
    "Departure_Time",
    "Distance"
]].head(20)

     Train_No  Station_Name        Arrival_time      Departure_Time  Distance
3         107   MADGOAN JN. 1900-01-01 12:10:00 1900-01-01 00:00:00        78
7         108  SAWANTWADI R 1900-01-01 22:25:00 1900-01-01 00:00:00        83
29        128   CHHATRAPATI 1900-01-01 17:45:00 1900-01-01 17:45:00       978
43        290  DELHI-SAFDAR 1900-01-01 02:30:00 1900-01-01 02:30:00      2694
55        401  VARANASI JN. 1900-01-01 10:00:00 1900-01-01 10:00:00      1618
60        421  SHRI MATA VA 1900-01-01 08:00:00 1900-01-01 08:00:00      1276
65        422   LUCKNOW JN. 1900-01-01 14:30:00 1900-01-01 14:30:00      1277
79        477         SIRSA 1900-01-01 15:20:00 1900-01-01 15:20:00      2616
88        502  AMBALA CANTT 1900-01-01 09:30:00 1900-01-01 09:30:00      1206
91        504   BATHINDA JN 1900-01-01 10:00:00 1900-01-01 10:00:00      1313
94        506       PATIALA 1900-01-01 15:45:00 1900-01-01 15:45:00      1161
96        557     PANJIPARA 1900-01-01 11:00:00 1900-01-01 11:00:00      1301
99        604  AMRITSAR JN. 1900-01-01 16:00:00 1900-01-01 16:00:00      1429
117      1011  NAGPUR JN.(C 1900-01-01 14:20:00 1900-01-01 14:20:00       841
127      1037  SAWANTWADI R 1900-01-01 10:30:00 1900-01-01 10:30:00       513
137      1038  LOKMANYA TIL 1900-01-01 00:20:00 1900-01-01 00:20:00       503
148      1045       KARMALI 1900-01-01 11:00:00 1900-01-01 11:00:00       563
172      1119       KARMALI 1900-01-01 20:30:00 1900-01-01 20:30:00      1329
196      1120          AJNI 1900-01-01 22:00:00 1900-01-01 22:00:00      1319
210      1122    CST-MUMBAI 1900-01-01 10:30:00 1900-01-01 10:30:00       569

In [26]:
df = df.sort_values(
    ["Train_No", "Route_Number", "SN"]
).reset_index(drop=True)
df.head(10)

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0
5,2,108,KRMI,265,232,199,166,KARMALI,1,1900-01-01 21:04:00,1900-01-01 21:06:00,33
6,3,108,THVM,355,304,253,202,THIVIM,1,1900-01-01 21:26:00,1900-01-01 21:28:00,51
7,4,108,SWV,515,432,349,266,SAWANTWADI R,1,1900-01-01 22:25:00,1900-01-01 00:00:00,83
8,1,128,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 19:40:00,1900-01-01 19:40:00,0
9,2,128,KRMI,265,232,199,166,KARMALI,1,1900-01-01 20:18:00,1900-01-01 20:20:00,33

In [24]:
train_journey = df.groupby("Train_No").agg(
    Start_Station=("Station_Name", "first"),
    End_Station=("Station_Name", "last"),
    Start_Time=("Departure_Time", "first"),
    End_Time=("Arrival_time", "last"),
    Total_Distance=("Distance", "max"),
    Number_of_Stops=("Station_Name", "count")
).reset_index()

In [27]:
train_journey.head(20)

,Train_No,Start_Station,End_Station,Start_Time,End_Time,Total_Distance,Number_of_Stops
0,107,SAWANTWADI R,MADGOAN JN.,1900-01-01 10:25:00,1900-01-01 12:10:00,78,4
1,108,MADGOAN JN.,SAWANTWADI R,1900-01-01 20:30:00,1900-01-01 22:25:00,83,4
2,128,MADGOAN JN.,CHHATRAPATI,1900-01-01 19:40:00,1900-01-01 17:45:00,978,22
3,290,DELHI-SAFDAR,DELHI-SAFDAR,1900-01-01 18:30:00,1900-01-01 02:30:00,2694,14
4,401,AURANGABAD,VARANASI JN.,1900-01-01 21:30:00,1900-01-01 10:00:00,1618,12
5,421,LUCKNOW JN.,SHRI MATA VA,1900-01-01 23:00:00,1900-01-01 08:00:00,1276,5
6,422,SHRI MATA VA,LUCKNOW JN.,1900-01-01 11:45:00,1900-01-01 14:30:00,1277,5
7,477,SIRSA,SIRSA,1900-01-01 12:10:00,1900-01-01 15:20:00,2616,14
8,502,RAJENDRANAGA,AMBALA CANTT,1900-01-01 10:30:00,1900-01-01 09:30:00,1206,9
9,504,PATNA JN.,BATHINDA JN,1900-01-01 09:00:00,1900-01-01 10:00:00,1313,3
10,506,PATNA JN.,PATIALA,1900-01-01 14:15:00,1900-01-01 15:45:00,1161,3
11,557,URKURA,PANJIPARA,1900-01-01 23:30:00,1900-01-01 11:00:00,1301,2
12,604,PATNA JN.,AMRITSAR JN.,1900-01-01 12:30:00,1900-01-01 16:00:00,1429,3
13,1011,CST-MUMBAI,NAGPUR JN.(C,1900-01-01 00:20:00,1900-01-01 14:20:00,841,18
14,1037,LOKMANYA TIL,SAWANTWADI R,1900-01-01 01:10:00,1900-01-01 10:30:00,513,10
15,1038,SAWANTWADI R,LOKMANYA TIL,1900-01-01 14:05:00,1900-01-01 00:20:00,503,10
16,1045,LOKMANYA TIL,KARMALI,1900-01-01 01:10:00,1900-01-01 11:00:00,563,11
17,1119,AJNI,KARMALI,1900-01-01 19:50:00,1900-01-01 20:30:00,1329,24
18,1120,KARMALI,AJNI,1900-01-01 21:30:00,1900-01-01 22:00:00,1319,24
19,1122,KARMALI,CST-MUMBAI,1900-01-01 22:30:00,1900-01-01 10:30:00,569,14

In [28]:
print("Total Trains:", len(train_journey))

Total Trains: 11113

In [29]:
train_journey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11113 entries, 0 to 11112
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Train_No         11113 non-null  int64
 1   Start_Station    11113 non-null  object
 2   End_Station      11113 non-null  object
 3   Start_Time       11113 non-null  datetime64[ns]
 4   End_Time         11113 non-null  datetime64[ns]
 5   Total_Distance   11113 non-null  int64
 6   Number_of_Stops  11113 non-null  int64
dtypes: datetime64[ns](2), int64(3), object(2)
memory usage: 607.9+ KB

In [30]:
train_journey["Start_Time_Calc"] = train_journey["Start_Time"]
train_journey["End_Time_Calc"] = train_journey["End_Time"]

In [31]:
train_journey[
    ["Train_No", "Start_Time", "End_Time",
     "Start_Time_Calc", "End_Time_Calc"]
].head(10)

,Train_No,Start_Time,End_Time,Start_Time_Calc,End_Time_Calc
0,107,1900-01-01 10:25:00,1900-01-01 12:10:00,1900-01-01 10:25:00,1900-01-01 12:10:00
1,108,1900-01-01 20:30:00,1900-01-01 22:25:00,1900-01-01 20:30:00,1900-01-01 22:25:00
2,128,1900-01-01 19:40:00,1900-01-01 17:45:00,1900-01-01 19:40:00,1900-01-01 17:45:00
3,290,1900-01-01 18:30:00,1900-01-01 02:30:00,1900-01-01 18:30:00,1900-01-01 02:30:00
4,401,1900-01-01 21:30:00,1900-01-01 10:00:00,1900-01-01 21:30:00,1900-01-01 10:00:00
5,421,1900-01-01 23:00:00,1900-01-01 08:00:00,1900-01-01 23:00:00,1900-01-01 08:00:00
6,422,1900-01-01 11:45:00,1900-01-01 14:30:00,1900-01-01 11:45:00,1900-01-01 14:30:00
7,477,1900-01-01 12:10:00,1900-01-01 15:20:00,1900-01-01 12:10:00,1900-01-01 15:20:00
8,502,1900-01-01 10:30:00,1900-01-01 09:30:00,1900-01-01 10:30:00,1900-01-01 09:30:00
9,504,1900-01-01 09:00:00,1900-01-01 10:00:00,1900-01-01 09:00:00,1900-01-01 10:00:00

In [32]:
train_journey["Journey_Duration"] = (
    train_journey["End_Time_Calc"] -
    train_journey["Start_Time_Calc"]
).dt.total_seconds() / 60

In [34]:
train_journey.loc[
    train_journey["Journey_Duration"] < 0,
    "Journey_Duration"
] += 24 * 60   // 24 * 60 means 1,440 minutes = 24 hours.

In [35]:
train_journey[
    ["Train_No", "Start_Station", "End_Station",
     "Start_Time", "End_Time",
     "Total_Distance", "Number_of_Stops",
     "Journey_Duration"]
].head(20)

,Train_No,Start_Station,End_Station,Start_Time,End_Time,Total_Distance,Number_of_Stops,Journey_Duration
0,107,SAWANTWADI R,MADGOAN JN.,1900-01-01 10:25:00,1900-01-01 12:10:00,78,4,105.0
1,108,MADGOAN JN.,SAWANTWADI R,1900-01-01 20:30:00,1900-01-01 22:25:00,83,4,115.0
2,128,MADGOAN JN.,CHHATRAPATI,1900-01-01 19:40:00,1900-01-01 17:45:00,978,22,1325.0
3,290,DELHI-SAFDAR,DELHI-SAFDAR,1900-01-01 18:30:00,1900-01-01 02:30:00,2694,14,480.0
4,401,AURANGABAD,VARANASI JN.,1900-01-01 21:30:00,1900-01-01 10:00:00,1618,12,750.0
5,421,LUCKNOW JN.,SHRI MATA VA,1900-01-01 23:00:00,1900-01-01 08:00:00,1276,5,540.0
6,422,SHRI MATA VA,LUCKNOW JN.,1900-01-01 11:45:00,1900-01-01 14:30:00,1277,5,165.0
7,477,SIRSA,SIRSA,1900-01-01 12:10:00,1900-01-01 15:20:00,2616,14,190.0
8,502,RAJENDRANAGA,AMBALA CANTT,1900-01-01 10:30:00,1900-01-01 09:30:00,1206,9,1380.0
9,504,PATNA JN.,BATHINDA JN,1900-01-01 09:00:00,1900-01-01 10:00:00,1313,3,60.0
10,506,PATNA JN.,PATIALA,1900-01-01 14:15:00,1900-01-01 15:45:00,1161,3,90.0
11,557,URKURA,PANJIPARA,1900-01-01 23:30:00,1900-01-01 11:00:00,1301,2,690.0
12,604,PATNA JN.,AMRITSAR JN.,1900-01-01 12:30:00,1900-01-01 16:00:00,1429,3,210.0
13,1011,CST-MUMBAI,NAGPUR JN.(C,1900-01-01 00:20:00,1900-01-01 14:20:00,841,18,840.0
14,1037,LOKMANYA TIL,SAWANTWADI R,1900-01-01 01:10:00,1900-01-01 10:30:00,513,10,560.0
15,1038,SAWANTWADI R,LOKMANYA TIL,1900-01-01 14:05:00,1900-01-01 00:20:00,503,10,615.0
16,1045,LOKMANYA TIL,KARMALI,1900-01-01 01:10:00,1900-01-01 11:00:00,563,11,590.0
17,1119,AJNI,KARMALI,1900-01-01 19:50:00,1900-01-01 20:30:00,1329,24,40.0
18,1120,KARMALI,AJNI,1900-01-01 21:30:00,1900-01-01 22:00:00,1319,24,30.0
19,1122,KARMALI,CST-MUMBAI,1900-01-01 22:30:00,1900-01-01 10:30:00,569,14,720.0

In [36]:
print(
    "Journey durations <= 0:",
    (train_journey["Journey_Duration"] <= 0).sum()
)

Journey durations <= 0: 6

In [37]:
print(
    "Missing journey durations:",
    train_journey["Journey_Duration"].isnull().sum()
)

Missing journey durations: 0

In [38]:
train_journey["Journey_Duration"].describe()

count    11113.000000
mean       276.013498
std        321.166943
min          0.000000
25%         61.000000
50%        132.000000
75%        365.000000
max       1435.000000
Name: Journey_Duration, dtype: float64

In [39]:
train_journey[
    train_journey["Journey_Duration"] > 24 * 60
][[
    "Train_No",
    "Start_Station",
    "End_Station",
    "Start_Time",
    "End_Time",
    "Journey_Duration"
]].head(20)

Empty DataFrame
Columns: [Train_No, Start_Station, End_Station, Start_Time, End_Time, Journey_Duration]
Index: []

In [40]:
model_data = train_journey[[
    "Train_No",
    "Start_Station",
    "End_Station",
    "Total_Distance",
    "Number_of_Stops",
    "Journey_Duration"
]].copy()

In [41]:
model_data.head()

,Train_No,Start_Station,End_Station,Total_Distance,Number_of_Stops,Journey_Duration
0,107,SAWANTWADI R,MADGOAN JN.,78,4,105.0
1,108,MADGOAN JN.,SAWANTWADI R,83,4,115.0
2,128,MADGOAN JN.,CHHATRAPATI,978,22,1325.0
3,290,DELHI-SAFDAR,DELHI-SAFDAR,2694,14,480.0
4,401,AURANGABAD,VARANASI JN.,1618,12,750.0

In [43]:
model_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11113 entries, 0 to 11112
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Train_No          11113 non-null  int64
 1   Start_Station     11113 non-null  object
 2   End_Station       11113 non-null  object
 3   Total_Distance    11113 non-null  int64
 4   Number_of_Stops   11113 non-null  int64
 5   Journey_Duration  11113 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 521.1+ KB

In [46]:
model_data.describe()

           Train_No  Total_Distance  Number_of_Stops  Journey_Duration
count  11113.000000    11113.000000     11113.000000      11113.000000
mean   49190.570413      348.870242        16.743814        276.013498
std    28515.986645      596.179751        12.993123        321.166943
min      107.000000        1.000000         2.000000          0.000000
25%    22607.000000       38.000000         8.000000         61.000000
50%    47174.000000       82.000000        15.000000        132.000000
75%    68012.000000      324.000000        22.000000        365.000000
max    99908.000000     4260.000000       118.000000       1435.000000

In [47]:
model_data.isnull().sum()

Train_No            0
Start_Station       0
End_Station         0
Total_Distance      0
Number_of_Stops     0
Journey_Duration    0
dtype: int64

In [48]:
model_data.to_csv(
    "train_journey_cleaned.csv",
    index=False
)

## Level 2 Summary

The train journey dataset was cleaned and transformed from station-level records into a train-level dataset.

The preprocessing steps included checking and handling duplicate records, inspecting missing values, converting arrival and departure times into datetime format, identifying journeys that cross midnight, and calculating total journey duration.

The main machine learning input features created were total distance and number of stops, while journey duration was created as the target variable.

The cleaned train-level dataset was saved as `train_journey_cleaned.csv` for use in the next level.